<?php
$data = array (
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => '腕表',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '189',
    'name' => '腕表',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '男表',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '69',
    'level' => 1,
    'id' => '146',
    'name' => '男表',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '女表',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 1,
    'id' => '147',
    'name' => '女表',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '选表中心',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '148',
    'name' => '选表中心',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '表带',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '149',
    'name' => '表带',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '情侣',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '186',
    'name' => '情侣',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '特惠',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '187',
    'name' => '特惠',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '新品',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '188',
    'name' => '新品',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '钻石',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '58',
    'name' => '钻石',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '对戒',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '164',
    'name' => '对戒',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '钻戒',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '钻戒',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '裸钻',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '裸钻',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '吊坠',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '吊坠',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '耳钉',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '耳钉',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '手链',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '手链',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '首饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '15',
    'goods_num' => 0,
    'level' => 0,
    'id' => '27',
    'name' => '首饰',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '项饰/吊坠',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '项饰/吊坠',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '手镯/手链',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '手镯/手链',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '戒指/指环',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '戒指/指环',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '胸饰',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '胸饰',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '耳饰',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '耳饰',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '挂饰',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '挂饰',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '摆件',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '摆件',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '丝巾扣',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '丝巾扣',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '首饰套装',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '首饰套装',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '宝石裸石',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '宝石裸石',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '头饰',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '头饰',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '眼镜',
    'measure_unit' => '30',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '192',
    'name' => '眼镜',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '纪念币',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '纪念币',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => '皮带',
    'measure_unit' => '20',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '194',
    'name' => '皮带',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '打火机',
    'measure_unit' => '20',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '191',
    'name' => '打火机',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '44',
    'name' => '服饰',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '手套',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '手套',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '童装',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '童装',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '女装',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '女装',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '男鞋',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '配饰',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '男装',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '男装',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '童鞋',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '童鞋',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '女鞋',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '香水',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '中档品牌',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => '中档品牌',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '菲拉格慕',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '菲拉格慕',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '爱宝时',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '爱宝时',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '赫柏林',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '赫柏林',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '天梭',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '天梭',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '浪琴',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '浪琴',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '男士香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '男士香水',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '博柏利',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '博柏利',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '宝格丽',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '宝格丽',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '淡香',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '阿迪达斯',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '阿迪达斯',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '海洋香调',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '海洋香调',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '中性香水',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '淡香',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '花果香调',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '花果香调',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '爱马仕',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '爱马仕',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '凯文克莱',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '凯文克莱',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '香水套装',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '香水套装',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '花果香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '花果香调',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '浪琴',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '浪琴',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '草木香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '草木香调',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '香体',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '香体',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '花香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '花香调',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => '关于我们',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '45',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '199',
    'name' => '关于我们',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '交易方式',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '46',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '200',
    'name' => '交易方式',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '包袋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '14',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '包袋',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '男包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '男包',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '女包',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '女包',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '手提包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '手提包',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '公文包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '公文包',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '双肩包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '双肩包',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '钱包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '钱包',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '手拿包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '手拿包',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '拉杆箱',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '旅行包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '旅行包',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '化妆包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '化妆包',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '小型皮具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '小型皮具',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '儿童包袋',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '儿童包袋',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '行李箱',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '行李箱',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '卡包',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '159',
    'name' => '卡包',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '价位功能',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '价位功能',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '价位范围',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '130',
    'name' => '价位范围',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '1000以下',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '165',
    'name' => '1000以下',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '3千~5千',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '3千~5千',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '5千~1万',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '5千~1万',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '1万~5万',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '166',
    'name' => '1万~5万',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '5万~10万',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '167',
    'name' => '5万~10万',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '10万以上',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '168',
    'name' => '10万以上',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '机芯',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '71',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '131',
    'name' => '机芯',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '机械表',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '机械表',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '自动机械',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '自动机械',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '手动机械',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '手动机械',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '石英表',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '石英表',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '特殊功能',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '72',
    'has_children' => '13',
    'goods_num' => 0,
    'level' => 1,
    'id' => '132',
    'name' => '特殊功能',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '防磁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '178',
    'name' => '防磁',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '世界时',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '175',
    'name' => '世界时',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '星期显示',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '星期显示',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '万年历',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '172',
    'name' => '万年历',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '月份显示',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '月份显示',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '防震',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '179',
    'name' => '防震',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '计时码表',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '176',
    'name' => '计时码表',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '夜光',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '173',
    'name' => '夜光',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '大三针',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '170',
    'name' => '大三针',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '动力储备显示',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '177',
    'name' => '动力储备显示',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '双时区',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '双时区',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '日期显示',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '日期显示',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '小三针',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '171',
    'name' => '小三针',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '威图手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '190',
    'name' => '威图手机',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '翻盖机',
    'measure_unit' => '30',
    'parent_id' => '190',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '196',
    'name' => '翻盖机',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '直板机',
    'measure_unit' => '30',
    'parent_id' => '190',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '197',
    'name' => '直板机',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '安卓系统机',
    'measure_unit' => '40',
    'parent_id' => '190',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '198',
    'name' => '安卓系统机',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '平板机',
    'measure_unit' => '50',
    'parent_id' => '190',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '195',
    'name' => '平板机',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '中国二手奢饰品工作委员会',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '201',
    'name' => '中国二手奢饰品工作委员会',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '时尚品牌',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '时尚品牌',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '时尚品牌',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '109',
    'name' => '时尚品牌',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => 'Guess',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => 'Guess',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '雅克利曼',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '雅克利曼',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => 'CK',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => 'CK',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '卡西欧',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '卡西欧',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '丰胸瘦身',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '丰胸瘦身',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '丰胸塑臀',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '丰胸塑臀',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '纤体瘦身',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '纤体瘦身',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '精油护理',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '精油护理',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '美发护发',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '62',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '美发护发',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '焗油',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '焗油',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '洗发',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '美发造型',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '美发造型',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '护发',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '染发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '染发',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '洗护套装',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '63',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '洗护套装',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '沐浴',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '护发养发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '护发养发',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '美体套装',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '美体套装',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '保湿',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '品牌馆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '150',
    'name' => '品牌馆',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '热销',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '151',
    'name' => '热销',
  ),
);
?>